#### 1- Create a numpy array of shape (3, 4) and assign random integers between 1 and 10 to every element.

In [1]:
import numpy as np

In [14]:
random_arr = np.random.randint(1,11, (3,4))
print(random_arr)

[[ 2  9  2 10]
 [ 7  2  8  9]
 [ 9  9  9 10]]


#### 2- Find the maximum value in the array created in step 1.

In [15]:
max_num = random_arr.max()
print(f'Maximum value in array: {max_num}')

Maximum value in array: 10


#### 3- Calculate the mean value of each row in the array.


In [21]:
mean_by_row = np.mean(random_arr, axis = 1)
print(f'Mean of each row: {mean_by_row}')


Mean of each row: [5.75 6.5  9.25]


#### 4- Reshape the array from step 1 into a shape of (2, 6).

In [23]:
new_arr = random_arr.reshape(2,6)
print(f'Reshaped array : {new_arr}')

Reshaped array : [[ 2  9  2 10  7  2]
 [ 8  9  9  9  9 10]]


#### 5- Multiply each element in the array by 2.

In [26]:
multiply_2 = random_arr*2
print(multiply_2)

[[ 4 18  4 20]
 [14  4 16 18]
 [18 18 18 20]]


#### 6- Create a numpy array with values ranging from 0 to 9. Extract the odd numbers from the array.

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
odd_array = arr[arr % 2 !=0]
print(f'Odd numbers from array {odd_array}')

odd numbers from array [1 3 5 7 9]


#### 7- Create a 3x3 identity matrix using numpy.

In [58]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8- Create a 5x5 array with random values and normalize it (subtract the mean and divide by the standard deviation of the array).

In [65]:
rand_arr = np.random.randn(5,5)
# Mean of array
mean_arr = rand_arr.mean()
stdv_arr = rand_arr.std()

print(f'Mean of array: {mean_arr} \n standard deviation of array: {stdv_arr}')

Mean of array: 0.10121096968599685 
 standard deviation of array: 1.0994136914740862


In [67]:
# Normalization of array 
normalized_array = (rand_arr-mean_arr)/stdv_arr
print(normalized_array)

[[-0.42570063 -0.53700285 -0.13082565 -1.04202881  1.54057695]
 [ 1.2844183  -0.2403385   0.70894515 -1.51417252  1.51753613]
 [-0.33153963  1.17148933  0.15392979 -0.72458899  1.27620805]
 [ 0.94070405  1.01904968 -1.08250725 -1.31244868 -0.18327492]
 [ 0.21918599 -2.32239511 -0.4166064   0.094999    0.33638751]]


#### 9- Perform element-wise multiplication between two arrays of the same shape.

In [70]:
arr1 = np.random.randint(1,50,(3,3))
arr2 = np.random.randint(1,20, (3,3))

In [73]:
multiplied_array = arr1*arr2
print(multiplied_array)

[[ 45 282 374]
 [369 720  28]
 [304  30 555]]


#### 10 - Given an array of heights in centimeters, convert them to inches (1 inch = 2.54 cm).

In [76]:
height_in_cm = np.array([160, 170, 180, 190])
# convert height in inch 

height_in_inch=height_in_cm/2.54

print(f'Height in inches: {height_in_inch}')

Height in inches: [62.99212598 66.92913386 70.86614173 74.80314961]


#### 11 - Create a 1D array of numbers from 0 to 9. Replace all odd numbers with -1.

In [78]:
arr_0_9 = np.arange(10)
arr_0_9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr_0_9[arr_0_9 % 2 != 0] = -1
print(arr_0_9)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Create a 2D array with random values and find the indices of the maximum and minimum values.

In [92]:
arr_2d = np.random.randint(10,101, (3,5))

In [99]:
arr_2d

index of maximum number (1, 0) /n index of minium number (1, 2)


In [100]:
max_index = np.unravel_index(np.argmax(arr_2d), arr_2d.shape)
min_index = np.unravel_index(np.argmin(arr_2d), arr_2d.shape) 
print(f'index of maximum number {max_index} /n index of minium number {min_index}')

index of maximum number (1, 0) /n index of minium number (1, 2)
